# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 00:04
from __future__ import unicode_literals

import bibliotek.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', bibliotek.models.StrictForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='bibliotek.Author')),
            ],
        ),
    ]
