# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 07:23
from __future__ import unicode_literals

import bibliotek.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digits', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=bibliotek.models.StrictOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='bibliotek.ISBN'),
        ),
    ]
